on:
  push:
    branches:
      - develop
jobs:
  build:
    name: 🔨 Build distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 🏗 Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 🏗 Install build dependencies
        run: |
          python -m pip install wheel octoprint --user
      - name: 🔨 Build a source zip
        run: |
          python setup.py sdist --formats=zip
      - name: ⬆ Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

  test-install:
    name: Installation tests
    needs: build
    strategy:
      matrix:
        python: ["2.7", "3.7", "3.8"]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: ⬇ Download build result
        uses: actions/download-artifact@v1
        with:
          name: dist
          path: dist
      - name: Install dependencies
        run: |
          python -m pip install --upgrade wheel setuptools pip
          python -m pip install octoprint
      - name: Test install of package
        run: |
          python -m pip install dist/Google_Drive_Backup-*.zip

  release:
    name: Update Release Numbers
    needs:
      - build
      - test-install
    runs-on: ubuntu-latest
    steps:
      - uses: paulhatch/semantic-version@v3
        with:
          # The branch to count commits on
          branch: "master"
          # The prefix to use to identify tags
          tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a
          # major (breaking) change
          major_pattern: "#MAJOR"
          # Same as above except indicating a minor change
          minor_pattern: "#MINOR"
          # A string to determine the format of the version output
          format: "${major}.${minor}.${patch}-prerelease.${increment}"

  generate_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: master, rc, develop
        DEFAULT_BUMP: patch
    
  upload-asset:
    name: Upload asset to release
    runs-on: ubuntu-latest
    needs:
      - build
      - test-install
      - release
    steps:
      - name: ⬇ Download build result
        uses: actions/download-artifact@v1
        with:
          name: dist
          path: dist
      - name: Rename to release.zip
        run: |
          cp dist/Google_Drive_Backup-*.zip release.zip
      - name: Generate Release and Artifacts
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest Development Build"
          files: |
            release.zip