
on:
  pull_request_target:
   types: [opened, labeled, unlabeled, synchronize]

jobs:
  check_pr_labels:
    runs-on: ubuntu-latest
    name: Verify that the PR has a valid label
    steps:
      - name: Verify PR label action
        uses: NathanielHill/check-pr-label-action@v4.0.0
        with:
            github-token: '${{ secrets.GITHUB_TOKEN }}'
            valid-labels: 'bump:minor, bump:major, bump:patch'